=== datacite/schema/source/archive/kernel-2.2/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision history
     2010-08-26   Complete revision according to new common specification by the metadata work group after review. AJH, DTIC
	 2010-11-17 Revised to current state of kernel review, FZ, TIB 
	 2011-01-17 Complete revision after community review. FZ, TIB
	 2011-03-17 Release of v2.1: added a namespace; mandatory properties got minLength; changes in the definitions of relationTypes
	 IsDocumentedBy/Documents and isCompiledBy/Compiles; changes type of property "Date" from xs:date to xs:string. FZ, TIB
	 2011-06-27 v2.2: namespace: kernel-2.2, additions to controlled lists "resourceType", "contributorType", "relatedIdentifierType", and "descriptionType". Removal of intermediate include-files.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://datacite.org/schema/kernel-2.2" targetNamespace="http://datacite.org/schema/kernel-2.2" elementFormDefault="qualified" xml:lang="EN">
	<xs:include schemaLocation="include/datacite-titleType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-contributorType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-dateType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-resourceType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relationType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relatedIdentifierType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-descriptionType-v2.xsd"/>
	<xs:element name="resource">
		<xs:annotation>
			<xs:documentation>
	Root element of a single record. This wrapper element is for XML implementation only and is not defined in the DataCite DOI standard.
        Note: This is the case for any wrapper element within this schema!</xs:documentation>
			<xs:documentation>No content in this wrapper element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--REQUIRED FIELDS-->
				<xs:element name="identifier">
					<xs:annotation>
						<xs:documentation>A persistent identifier that identifies a resource.</xs:documentation>
						<xs:documentation>Currently, only DOI is allowed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="doiType">
								<xs:attribute name="identifierType" use="required" fixed="DOI"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="creators">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="creator" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name.</xs:documentation>
									<xs:documentation>Format: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="creatorName">
											<xs:simpleType>
												<xs:restriction base="nonemptycontentStringType"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="nonemptycontentStringType">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="titles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>A name or title by which a resource is known.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="nonemptycontentStringType">
											<xs:attribute name="titleType" type="titleType" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher">
					<xs:annotation>
						<xs:documentation>A holder of the data (including archives as appropriate) or institution which submitted the work. Any others may be listed as contributors. This property will be used to formulate the citation, so consider the prominence of the role.</xs:documentation>
						<xs:documentation>Examples: World Data Center for Climate (WDCC); GeoForschungsZentrum Potsdam (GFZ); Geological Institute, University of Tokyo </xs:documentation>
						<xs:documentation>In the case of datasets, "publish" is understood to mean making the data available to the community of researchers.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="nonemptycontentStringType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="publicationYear">
					<xs:annotation>
						<xs:documentation>Year when the data is made publicly available. If an embargo period has been in effect, use the date when the embargo period ends.</xs:documentation>
						<xs:documentation>YYYY</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="yearType"/>
					</xs:simpleType>
				</xs:element>
				<!--OPTIONAL FIELDS-->
				<xs:element name="subjects" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="subject" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Subject, keywords, classification codes, or key phrases describing the resource.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="subjectScheme" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contributors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="contributor" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The institution or person responsible for collecting, creating, or otherwise contributing to the development of the dataset.</xs:documentation>
									<xs:documentation>The personal name format should be: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="contributorName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="contributorType" type="contributorType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dates" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Different dates relevant to the work.</xs:documentation>
									<xs:documentation>YYYY or YYYY-MM-DD or any other format described in W3CDTF (http://www.w3.org/TR/NOTE-datetime) </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="dateType" type="dateType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" type="xs:language" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Primary language of the resource. Allowed values from: ISO 639-2/B, ISO 639-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resourceType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The type of a resource. You may enter an additional free text description.</xs:documentation>
					</xs:annotation>
					<xs:complexType mixed="true">
						<xs:annotation>
							<xs:documentation>Use this attribute to choose the general type of the resource from the controlled list.</xs:documentation>
						</xs:annotation>
						<xs:attribute name="resourceTypeGeneral" type="resourceType" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="alternateIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alternateIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>An identifier other than the primary identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. The format is open</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="alternateIdentifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="relatedIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relatedIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Identifiers of related resources. Use this property to indicate subsets of properties, as appropriate.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="relatedIdentifierType" type="relatedIdentifierType" use="required"/>
											<xs:attribute name="relationType" type="relationType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sizes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="size" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Unstructures size information about the resource. </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formats" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="format" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Technical format of the resource.</xs:documentation>
									<xs:documentation>Use file extension or MIME type where possible.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="version" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Version number of the resource. If the primary resource has changed the version number increases.</xs:documentation>
						<xs:documentation>Register a new DOI (or primary identifier) when the version of the resource changes to enable the citation of the exact version of a research dataset (or other resource). May be used in conjunction with properties 11 and 12 (AlternateIdentifier and RelatedIdentifier) to indicate various information updates.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="rights" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Any rights information for this resource. Provide a rights management statement for the resource or reference a service providing such information. Include embargo information if applicable.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="descriptions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:choice>
										<xs:element name="br" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="descriptionType" type="descriptionType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="lastMetadataUpdate" type="xs:date" use="optional"/>
			<xs:attribute name="metadataVersionNumber" type="xs:integer" use="optional"/>
			<!--ADMINISTRATIVE FIELDS-->
		</xs:complexType>
	</xs:element>
	<!-- TYPE DECLARATIONS -->
	<!-- defines the value for a DOI: DOI must start with "10."  -->
	<xs:simpleType name="doiType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[1][0][/.].*"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- defines value for mandatory fields -->
	<xs:simpleType name="nonemptycontentStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameId">
		<xs:attribute name="nameIdentifier" type="xs:string" use="optional"/>
		<xs:attribute name="nameIdentifierScheme" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- defines the value for a year -->
	<xs:simpleType name="yearType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[\d]{4}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== datacite/schema/source/meta/kernel-4.3/example/datacite-example-relationTypeIsIdenticalTo-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  <identifier identifierType="DOI">10.5072/10.CPoS-example</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Kreyenfeld, Michaela</creatorName>
      <givenName>Michaela</givenName>
      <familyName>Kreyenfeld</familyName>
      <nameIdentifier nameIdentifierScheme="ISNI" schemeURI="http://isni.org/isni/">0000000117540116</nameIdentifier>
    </creator>
    <creator>
      <creatorName nameType="Personal">Hornung, Anne</creatorName>
      <givenName>Anne</givenName>
      <familyName>Hornung</familyName>
      <nameIdentifier nameIdentifierScheme="VIAF" schemeURI="http://viaf.org/viaf/">304639093</nameIdentifier>
    </creator>
    <creator>
      <creatorName nameType="Personal">Kubisch, Karolin</creatorName>
      <givenName>Karolin</givenName>
      <familyName>Kubisch</familyName>
      <nameIdentifier nameIdentifierScheme="VIAF" schemeURI="http://viaf.org/viaf/">303937450</nameIdentifier>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">The German Generations and Gender Survey</title>
    <title xml:lang="en" titleType="Subtitle">Some Critical Reflections on the Validity of Fertility Histories</title>
  </titles>
  <publisher xml:lang="en">Federal Institute for Population Research, Germany</publisher>
  <publicationYear>2013</publicationYear>
  <subjects>
    <subject xml:lang="en">Fertility</subject>
    <subject xml:lang="en">Marriage</subject>
    <subject xml:lang="en">Germany</subject>
    <subject xml:lang="en">Data validation</subject>
    <subject xml:lang="en">Mikrozensus</subject>
    <subject xml:lang="en">Gender survey</subject>
    <subject xml:lang="en" schemeURI="http://www.gesis.org/en/services/research/tools-for-searching/classification" subjectScheme="GESIS">10300 Demography, Population Research</subject>
  </subjects>
  <contributors>
    <contributor contributorType="Editor">
      <contributorName xml:lang="en" nameType="Organizational">Federal Institute for Population Research</contributorName>
      <nameIdentifier nameIdentifierScheme="ISNI" schemeURI="http://isni.org/isni/">0000000094455866</nameIdentifier>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Text">Article</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="internal ID">da|ra.14.103</alternateIdentifier>
  </alternateIdentifiers>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URN" relationType="IsIdenticalTo">urn:nbn:de:bib-cpos-2013-02en8</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsIdenticalTo">10.4232/10.CPoS-2013-02en</relatedIdentifier>
  </relatedIdentifiers>
  <formats>
    <format>PDF</format>
  </formats>
  <version>1</version>
  <rightsList>
   <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="CC-BY-NC-ND-3.0" rightsURI="http://creativecommons.org/licenses/by-nc-nd/3.0/deed">Creative Commons License: Attribution-NonCommercial-NoDerivs 3.0 Unported</rights>
  </rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="SeriesInformation">Comparative Population Studies Vol 38, No 1 (2013)</description>
    <description xml:lang="en" descriptionType="Abstract">This paper validates the fertility histories of the German Generations and Gender Survey (GGS). Focusing on the cohorts 1930-69 of West German women, the total number of children, the parity distribution and the parity progression ratios are comparedto external sources. One major result from this validation is that the German GGS understates the fertility for the older cohorts and overstates it for the younger ones.</description>
  </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4/example/datacite-example-award-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/p1zt-4c67</identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">The Research Trust</creatorName>
            <nameIdentifier nameIdentifierScheme="ROR" schemeURI="https://ror.org/">https://ror.org/01abcde23</nameIdentifier>
        </creator>
    </creators>
    <titles>
        <title>Enhancing metadata for inclusive research on entrenched disadvantage</title>
    </titles>
    <publisher publisherIdentifier="https://ror.org/01abcde23" publisherIdentifierScheme="ROR" schemeURI="https://ror.org/">The Research Trust</publisher>
    <publicationYear>2024</publicationYear>
    <resourceType resourceTypeGeneral="Award">Grant</resourceType>
    <contributors>
        <contributor contributorType="ProjectLeader">
            <contributorName nameType="Personal">Garcia, Sofia</contributorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org/">Arizona State University</affiliation>
        </contributor>
        <contributor contributorType="ProjectLeader">
            <contributorName nameType="Organizational">Arizona State University</contributorName>
            <nameIdentifier nameIdentifierScheme="ROR" schemeURI="https://ror.org/">https://ror.org/03efmqc40</nameIdentifier>
        </contributor>
        <contributor contributorType="Reviewer">
            <contributorName nameType="Personal">Nakamura, Yuki</contributorName>
            <givenName>Yuki</givenName>
            <familyName>Nakamura</familyName>
            <affiliation affiliationIdentifier="https://ror.org/01abcde23" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org/">The Research Trust</affiliation>
        </contributor>
    </contributors>
    <dates>
        <date dateType="Issued">2024-08-01</date>
        <date dateType="Valid">2025-01-01/2027-12-31</date>
        <date dateType="Updated" dateInformation="Extended">2028-01-01/2029-12-31</date>
    </dates>
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasOutput" resourceTypeGeneral="JournalArticle">10.21384/mw2e-x008</relatedIdentifier>
    </relatedIdentifiers>
    <sizes>
        <size>900000 USD</size>
    </sizes>
    <descriptions>
        <description descriptionType="Abstract">This funding award supports a project aimed at improving metadata practices to facilitate inclusive research on issues of entrenched disadvantage. The project focuses on creating robust, standardized metadata that accurately represents diverse populations and contexts.</description>
    </descriptions>
    <alternateIdentifiers>
        <alternateIdentifier alternateIdentifierType="URL">https://grants.net/123456</alternateIdentifier>
    </alternateIdentifiers>
</resource>

=== datacite/schema/source/meta/kernel-4.7/example/datacite-example-relationtypeinformation-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4"
    xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/0320-9g16</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Garcia, Sofia</creatorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">
                https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40"
                affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Arizona State
                University</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Comment on "Improving Metadata Quality in Scholarly Repositories"</title>
    </titles>
    <publisher>Global Open Research</publisher>
    <publicationYear>2025</publicationYear>
    <resourceType resourceTypeGeneral="Preprint" />
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="Other"
            relationTypeInformation="is reply to" resourceTypeGeneral="JournalArticle">10.82433/e34e-y143</relatedIdentifier>
    </relatedIdentifiers>
    <language>en</language>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">This preprint provides a response to
            the article "Improving Metadata Quality in Scholarly Repositories." It discusses
            additional considerations for enhancing metadata completeness, consistency, and
            interoperability. The authors highlight practical workflows, offer examples of common
            metadata challenges, and suggest strategies to improve discoverability and reuse of
            repository content.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.8/example/datacite-example-translation-original-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/pma6-nf93</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Green, Simon</creatorName>
        </creator>
    </creators>
    <titles>
        <title xml:lang="de">Klimawandel und Anpassungsstrategien</title>
    </titles>
    <publisher>Institut für Umweltforschung</publisher>
    <publicationYear>2022</publicationYear>
    <dates>
        <date dateType="Issued">2022-07-07</date>
    </dates>
    <resourceType resourceTypeGeneral="Report"/>
    <language>de</language>
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="HasTranslation">10.82433/45e5-xy14</relatedIdentifier>
    </relatedIdentifiers>
    <descriptions>
        <description xml:lang="de" descriptionType="Abstract">Dieser Bericht untersucht die Auswirkungen des Klimawandels und erkundet mögliche Anpassungsstrategien. Er befasst sich mit Themen wie extremen Wetterereignissen, Anpassungsmaßnahmen für städtische und ländliche Gebiete und politischen Empfehlungen zur Minderung von Klimarisiken.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.3/example/datacite-example-GeoLocation-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  <identifier identifierType="DOI">10.5072/geoPointExample</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Schumann, Kai</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Völker, David</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Weinrebe, Wilhelm Reiber</creatorName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">
      Gridded results of swath bathymetric mapping of Disko Bay, Western Greenland, 2007-2008
    </title>
  </titles>
  <publisher xml:lang="en">
    PANGAEA - Data Publisher for Earth &amp; Environmental Science
  </publisher>
  <publicationYear>2011</publicationYear>
  <subjects>
    <subject xml:lang="en" subjectScheme="DDC">551 Geology, hydrology, meteorology</subject>
  </subjects>
  <contributors>
    <contributor contributorType="HostingInstitution">
      <contributorName nameType="Organizational">
        IFM-GEOMAR Leibniz-Institute of Marine Sciences, Kiel University
      </contributorName>
      <nameIdentifier nameIdentifierScheme="ROR" schemeURI="http://ror.org/">https://ror.org/02h2x0161</nameIdentifier>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Dataset"/>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="Continues">10.5072/timeSeries</relatedIdentifier>
  </relatedIdentifiers>
  <sizes>
    <size>4 datasets</size>
  </sizes>
  <formats>
    <format>application/zip</format>
  </formats>
  <rightsList>
    <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="
CC-BY-3.0"  rightsURI="http://creativecommons.org/licenses/by/3.0/deed">Creative Commons Attribution-NoDerivs 2.0 Generic</rights></rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      A ship-based acoustic mapping campaign was conducted at the exit of Ilulissat Ice Fjord and in the sedimentary basin of Disko Bay to the west of the fjord mouth. Submarine landscape and sediment distribution patterns are interpreted in terms of
      glaciomarine facies types that are related to variations in the past position of the glacier front. In particular, asymmetric ridges that form a curved entity and a large sill at the fjord mouth may represent moraines hat depict at least two
      relatively stable positions of the ice front in the Disko Bay and at the fjord mouth. In this respect, Ilulissat Glacier shows prominent differences to the East Greenland Kangerlussuaq Glacier which is comparable in present size and present role for
      the ice discharge from the inland ice sheet. Two linear clusters of pockmarks in the center of the sedimentary basin seem to be linked to ongoing methane release due to dissociation of gas hydrates, a process fueled by climate warming in the Arctic
      realm.
    </description>
  </descriptions>
  <geoLocations>
    <geoLocation>
      <geoLocationPlace>Disko Bay</geoLocationPlace>
      <geoLocationPoint>
        <pointLongitude>-52.000000</pointLongitude>
        <pointLatitude>69.000000</pointLatitude>
      </geoLocationPoint>
    </geoLocation>
  </geoLocations>
</resource>
