=== datacite/schema/source/archive/kernel-2.2/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision history
     2010-08-26   Complete revision according to new common specification by the metadata work group after review. AJH, DTIC
	 2010-11-17 Revised to current state of kernel review, FZ, TIB 
	 2011-01-17 Complete revision after community review. FZ, TIB
	 2011-03-17 Release of v2.1: added a namespace; mandatory properties got minLength; changes in the definitions of relationTypes
	 IsDocumentedBy/Documents and isCompiledBy/Compiles; changes type of property "Date" from xs:date to xs:string. FZ, TIB
	 2011-06-27 v2.2: namespace: kernel-2.2, additions to controlled lists "resourceType", "contributorType", "relatedIdentifierType", and "descriptionType". Removal of intermediate include-files.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://datacite.org/schema/kernel-2.2" targetNamespace="http://datacite.org/schema/kernel-2.2" elementFormDefault="qualified" xml:lang="EN">
	<xs:include schemaLocation="include/datacite-titleType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-contributorType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-dateType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-resourceType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relationType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relatedIdentifierType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-descriptionType-v2.xsd"/>
	<xs:element name="resource">
		<xs:annotation>
			<xs:documentation>
	Root element of a single record. This wrapper element is for XML implementation only and is not defined in the DataCite DOI standard.
        Note: This is the case for any wrapper element within this schema!</xs:documentation>
			<xs:documentation>No content in this wrapper element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--REQUIRED FIELDS-->
				<xs:element name="identifier">
					<xs:annotation>
						<xs:documentation>A persistent identifier that identifies a resource.</xs:documentation>
						<xs:documentation>Currently, only DOI is allowed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="doiType">
								<xs:attribute name="identifierType" use="required" fixed="DOI"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="creators">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="creator" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name.</xs:documentation>
									<xs:documentation>Format: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="creatorName">
											<xs:simpleType>
												<xs:restriction base="nonemptycontentStringType"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="nonemptycontentStringType">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="titles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>A name or title by which a resource is known.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="nonemptycontentStringType">
											<xs:attribute name="titleType" type="titleType" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher">
					<xs:annotation>
						<xs:documentation>A holder of the data (including archives as appropriate) or institution which submitted the work. Any others may be listed as contributors. This property will be used to formulate the citation, so consider the prominence of the role.</xs:documentation>
						<xs:documentation>Examples: World Data Center for Climate (WDCC); GeoForschungsZentrum Potsdam (GFZ); Geological Institute, University of Tokyo </xs:documentation>
						<xs:documentation>In the case of datasets, "publish" is understood to mean making the data available to the community of researchers.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="nonemptycontentStringType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="publicationYear">
					<xs:annotation>
						<xs:documentation>Year when the data is made publicly available. If an embargo period has been in effect, use the date when the embargo period ends.</xs:documentation>
						<xs:documentation>YYYY</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="yearType"/>
					</xs:simpleType>
				</xs:element>
				<!--OPTIONAL FIELDS-->
				<xs:element name="subjects" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="subject" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Subject, keywords, classification codes, or key phrases describing the resource.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="subjectScheme" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contributors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="contributor" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The institution or person responsible for collecting, creating, or otherwise contributing to the development of the dataset.</xs:documentation>
									<xs:documentation>The personal name format should be: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="contributorName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="contributorType" type="contributorType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dates" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Different dates relevant to the work.</xs:documentation>
									<xs:documentation>YYYY or YYYY-MM-DD or any other format described in W3CDTF (http://www.w3.org/TR/NOTE-datetime) </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="dateType" type="dateType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" type="xs:language" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Primary language of the resource. Allowed values from: ISO 639-2/B, ISO 639-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resourceType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The type of a resource. You may enter an additional free text description.</xs:documentation>
					</xs:annotation>
					<xs:complexType mixed="true">
						<xs:annotation>
							<xs:documentation>Use this attribute to choose the general type of the resource from the controlled list.</xs:documentation>
						</xs:annotation>
						<xs:attribute name="resourceTypeGeneral" type="resourceType" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="alternateIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alternateIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>An identifier other than the primary identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. The format is open</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="alternateIdentifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="relatedIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relatedIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Identifiers of related resources. Use this property to indicate subsets of properties, as appropriate.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="relatedIdentifierType" type="relatedIdentifierType" use="required"/>
											<xs:attribute name="relationType" type="relationType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sizes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="size" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Unstructures size information about the resource. </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formats" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="format" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Technical format of the resource.</xs:documentation>
									<xs:documentation>Use file extension or MIME type where possible.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="version" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Version number of the resource. If the primary resource has changed the version number increases.</xs:documentation>
						<xs:documentation>Register a new DOI (or primary identifier) when the version of the resource changes to enable the citation of the exact version of a research dataset (or other resource). May be used in conjunction with properties 11 and 12 (AlternateIdentifier and RelatedIdentifier) to indicate various information updates.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="rights" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Any rights information for this resource. Provide a rights management statement for the resource or reference a service providing such information. Include embargo information if applicable.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="descriptions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:choice>
										<xs:element name="br" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="descriptionType" type="descriptionType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="lastMetadataUpdate" type="xs:date" use="optional"/>
			<xs:attribute name="metadataVersionNumber" type="xs:integer" use="optional"/>
			<!--ADMINISTRATIVE FIELDS-->
		</xs:complexType>
	</xs:element>
	<!-- TYPE DECLARATIONS -->
	<!-- defines the value for a DOI: DOI must start with "10."  -->
	<xs:simpleType name="doiType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[1][0][/.].*"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- defines value for mandatory fields -->
	<xs:simpleType name="nonemptycontentStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameId">
		<xs:attribute name="nameIdentifier" type="xs:string" use="optional"/>
		<xs:attribute name="nameIdentifierScheme" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- defines the value for a year -->
	<xs:simpleType name="yearType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[\d]{4}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== datacite/schema/source/meta/kernel-4.4/example/datacite-example-HasMetadata-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.2/metadata.xsd">
  <identifier identifierType="DOI">10.5072/example</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Mari, Bernard</creatorName>
      <givenName>Bernard</givenName>
      <familyName>Mari</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Puissegur, Marie-Pierre</creatorName>
      <givenName>Marie-Pierre</givenName>
      <familyName>Puissegur</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Barbry, Pascal</creatorName>
      <givenName>Pascal</givenName>
      <familyName>Barbry</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Lebrigand, Kevin</creatorName>
      <givenName>Kevin</givenName>
      <familyName>Lebrigand</familyName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">
      Identification of putative novel specific targets of mir-210 in A549 human adenocarcinoma cells
    </title>
  </titles>
  <publisher xml:lang="fr">
    Institut de Pharmacologie Moleculaire et Cellulaire (IPMC), CNRS UMR6097, Universite de Nice Sophia-Antipolis, 660 route des lucioles, 06560 Valbonne - Sophia-Antipolis, France
  </publisher>
  <publicationYear>2010</publicationYear>
  <subjects>
    <subject schemeURI="http://www.nlm.nih.gov/mesh/meshhome.html" subjectScheme="Mesh">Neoplasms</subject>
    <subject schemeURI="http://purl.obolibrary.org/obo/obi" subjectScheme="OBI">Transcription profiling</subject>
    <subject schemeURI="http://www.ncbi.nlm.nih.gov/Taxonomy/" subjectScheme="NCBITaxon">Homo sapiens</subject>
    <subject schemeURI="http://www.ebi.ac.uk/efo" subjectScheme="Mesh">A549</subject>
    <subject schemeURI="http://purl.obolibrary.org/obo/obi" subjectScheme="OBI">DNA microarray</subject>
  </subjects>
  <contributors>
    <contributor contributorType="HostingInstitution">
      <contributorName xml:lang="fr" nameType="Organizational">INIST-CNRS</contributorName>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Text">Experiment report</resourceType>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URL" relatedMetadataScheme="ISA-Tab" relationType="HasMetadata" schemeType="Text" schemeURI="http://isatab.sourceforge.net/docs/ISA-TAB_release-candidate-1_v1.0_24nov08.pdf">http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18695</relatedIdentifier>
  </relatedIdentifiers>
  <sizes>
    <size>183 ko</size>
    <size>3 pages</size>
  </sizes>
  <formats>
    <format>PDF</format>
  </formats>
  <rightsList>
    <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/"   rightsIdentifierScheme="SPDX" rightsIdentifier="CC-BY-NC-ND-3.0"  rightsURI="http://creativecommons.org/licenses/by-nc-nd/3.0/"/>  </rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      To identify putative novel specific targets of mir-210, we overexpressed miR-210 as well as miR-34a and a siRNA targeted against E2F3 in A549 human adenocarcinoma cells by transfecting them with synthetic pre-miRNAs or a synthetic negative pre-miRNA
      as control (miR-Neg). RNA samples were harvested at 48 hours post-transfection and 2 independent experiments performed in dye-swap: miR-210 versus miR-Neg ; miR-34a versus miR-Neg ; si-E2F3 versus miR-Neg ; si-control versus miR-Neg.
    </description>
  </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-2.2/example/datacite-metadata-sample-complicated-v2.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-2.2 http://schema.datacite.org/meta/kernel-2.2/metadata.xsd">
	<identifier identifierType="DOI">10.5072/testpub</identifier>
	<creators>
		<creator>
			<creatorName>Smith, John</creatorName>
		</creator>
		<creator>
			<creatorName>つまらないものですが</creatorName>
			<nameIdentifier nameIdentifierScheme="ISNI">abc123</nameIdentifier>
		</creator>
	</creators>
	<titles>
		<title>Właściwości rzutowań podprzestrzeniowych</title>
		<title titleType="TranslatedTitle">Translation of Polish titles</title>
	</titles>
	<publisher>Springer</publisher>
	<publicationYear>2010</publicationYear>
	<subjects>
		<subject subjectScheme="DDC">830 German &amp; related literatures</subject>
		<subject>Polish Literature</subject>
	</subjects>
	<contributors>
		<contributor contributorType="DataCollector">
			<contributorName>Doe, John</contributorName>
			<nameIdentifier nameIdentifierScheme="ORCID">456xyz</nameIdentifier>
		</contributor>
	</contributors>
	<dates>
		<date dateType="StartDate">2009-04-29</date>
		<date dateType="EndDate">2010-01-05</date>
	</dates>
	<language>GER</language>
	<resourceType resourceTypeGeneral="Text">Monograph</resourceType>
	<alternateIdentifiers>
		<alternateIdentifier alternateIdentifierType="ISBN">937-0-4523-12357-6</alternateIdentifier>
	</alternateIdentifiers>
	<relatedIdentifiers>
		<relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.5272/oldertestpub</relatedIdentifier>
	</relatedIdentifiers>
	<sizes>
		<size>256 pages</size>
	</sizes>
	<formats>
		<format>pdf</format>
	</formats>
	<version>2</version>
	<rights>CC by-nd</rights>
	<descriptions>
		<description descriptionType="Abstract">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</description>
	</descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.4/example/datacite-example-workflow-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.2/metadata.xsd">
  <identifier identifierType="DOI">10.5072/100044</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Luo, R</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Liu, B</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Xie, Y</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Li, Z</creatorName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">
      Software and supporting material for "SOAPdenovo2: An empirically improved memory-efficient short read de novo assembly"
    </title>
  </titles>
  <publisher xml:lang="en">GigaScience Database</publisher>
  <publicationYear>2012</publicationYear>
  <subjects>
    <subject xml:lang="en">DNA (Genetics)</subject>
    <subject xml:lang="en">Computer Program</subject>
  </subjects>
  <dates>
    <date dateType="Available">2012-12-13</date>
  </dates>
  <language>en</language>
  <resourceType resourceTypeGeneral="Workflow">Software</resourceType>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsReferencedBy">10.5072/2047-217X-1-1</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="Compiles">10.5072/100038</relatedIdentifier>
  </relatedIdentifiers>
  <sizes>
    <size>31 MB</size>
  </sizes>
  <rightsList>
    <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="CC0 1.0" rightsURI="http://creativecommons.org/publicdomain/zero/1.0/"/>  </rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      SOAPdenovo2 is the latest de novo genome assembly package from BGI's SOAP (short oligonucleotide analysis package) suite of tools (homepage here: http://soap.genomics.org.cn/). Compared to SOAPdenovo1, this new version has the advantage of a new
      algorithm design that reduces memory consumption in graph construction, resolves more repeat regions in contig assembly, increases coverage and length in scaffold construction, improves gap closure, and is optimized for large genomes. Using new
      sequencing data from the YH (Homo sapiens) diploid genome - the first sequenced Han Chinese individual, an updated assembly was produced (see dataset here: doi:10.5524/100038), with the N50 scores for the contig and scaffold being 3-fold and 50-fold
      longer, respectively, than the first published version. The genome coverage increased from 81.16% to 93.91%, and memory consumption was ~2/3 times lower during the point of largest memory consumption. Benchmarking with Assemblathon1 and GAGE datasets
      shows that SOAPdenovo2 greatly surpasses its predecessor SOAPdenovo1 and is competitive to other assemblers on both assembly length and accuracy. In order to facilitate readers to repeat and recreate these findings, configured packages with the
      compressed pipelines containing all of the necessary shell scripts and tools are available from the BGI FTP server (ftp://public.genomics.org.cn/BGI/SOAPdenovo2). The latest version of SOAPdenovo2 is available from Sourceforge:
      http://soapdenovo2.sourceforge.net/ These pipelines will also soon be made available from our data platform as Galaxy workflows: http://galaxy.cbiit.cuhk.edu.hk/
    </description>
  </descriptions>
</resource>

=== datacite/schema/meta/kernel-3/example/datacite-example-full-v3.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd" xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <identifier identifierType="DOI">10.5072/example-full</identifier>
    <creators>
        <creator>
            <creatorName>Miller, Elizabeth</creatorName>
            <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-5000-0007</nameIdentifier>
            <affiliation>DataCite</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en-us">Full DataCite XML Example</title>
        <title xml:lang="en-us" titleType="Subtitle">Demonstration of DataCite Properties.</title>
    </titles>
    <publisher>DataCite</publisher>
    <publicationYear>2014</publicationYear>
    <subjects>
        <subject xml:lang="en-us" schemeURI="http://dewey.info/" subjectScheme="dewey">000 computer science</subject>
    </subjects>
    <contributors>
        <contributor contributorType="ProjectLeader">
            <contributorName>Starr, Joan</contributorName>
            <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0002-7285-027X</nameIdentifier>
            <affiliation>California Digital Library</affiliation>
        </contributor>
    </contributors>
    <dates>
        <date dateType="Updated">2014-10-17</date>
    </dates>
    <language>en-us</language>
    <resourceType resourceTypeGeneral="Software">XML</resourceType>
    <alternateIdentifiers>
        <alternateIdentifier alternateIdentifierType="URL">http://schema.datacite.org/schema/meta/kernel-3.1/example/datacite-example-full-v3.1.xml</alternateIdentifier>
    </alternateIdentifiers>
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="URL" relationType="HasMetadata" relatedMetadataScheme="citeproc+json" schemeURI="https://github.com/citation-style-language/schema/raw/master/csl-data.json">http://data.datacite.org/application/citeproc+json/10.5072/example-full</relatedIdentifier>
        <relatedIdentifier relatedIdentifierType="arXiv" relationType="IsReviewedBy">arXiv:0706.0001</relatedIdentifier>
    </relatedIdentifiers>
    <sizes>
        <size>3KB</size>
    </sizes>
    <formats>
        <format>application/xml</format>
    </formats>
    <version>3.1</version>
    <rightsList>
        <rights rightsURI="http://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Universal</rights>
    </rightsList>
    <descriptions>
        <description xml:lang="en-us" descriptionType="Abstract">
            XML example of all DataCite Metadata Schema v3.1 properties.
        </description>
    </descriptions>
    <geoLocations>
        <geoLocation>
            <geoLocationPoint>31.233 -67.302</geoLocationPoint>
            <geoLocationBox>41.090 -71.032  42.893 -68.211</geoLocationBox>
            <geoLocationPlace>Atlantic Ocean</geoLocationPlace>
        </geoLocation>
    </geoLocations>
</resource>

=== datacite/schema/source/meta/kernel-4/example/datacite-example-audiovisual-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4"
    xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/9jbk-4c28</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Garcia, Sofia</creatorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">
                https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40"
                affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Arizona State
                University</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">DOIs in Action: Making Presentations More Discoverable</title>
    </titles>
    <publisher>International Metadata Forum</publisher>
    <publicationYear>2025</publicationYear>
    <dates>
        <date dateType="Issued">2025-08-11</date>
    </dates>
    <resourceType resourceTypeGeneral="Audiovisual">Conference presentation recording</resourceType>
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="URL" relationType="Other"
            relationTypeInformation="was presented at">https://example.org/metadata-forum-2025</relatedIdentifier>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsVariantFormOf"
            resourceTypeGeneral="Presentation">10.82433/v14f-gk24</relatedIdentifier>
    </relatedIdentifiers>
    <language>en</language>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">Conference presentations are often
            overlooked in discovery and citation systems. This presentation demonstrates practical
            workflows for assigning DOIs to presentations, linking them to related datasets and
            publications, and embedding identifiers in slide decks for easy sharing. By applying
            these strategies, researchers can increase the visibility, impact, and reusability of
            their talks beyond the event itself.</description>
    </descriptions>
</resource>
